[package]
name = "Carnister"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.0.0"
dotenv = "0.15.0"
indicatif = "0.18.0"
regex = "1.11.1"
reqwest = {version = "0.12.22", features = ["json"]}
serde_json = "1.0.140"
tokio = { version = "1.46.1", features = ["full"] }

